use video tile for description if short description is empty
brightcove/videojs-schema pull request #24
Opened 2021-05-24 05:16 UTC by lanmengyujing

2021-05-24 07:46 UTC, mister-ben requested changes
This makes sense if it produces valid schema when no description is set, notwithstanding that having separate values may be better for SEO.

2021-05-24 07:46 UTC, mister-ben commented on src/plugin.js
>        ld.description = this.mediainfo.longDescription || this.mediainfo.description;
This should also fall back to name.

2021-05-24 08:35 UTC, lanmengyujing commented on src/plugin.js
>        ld.description = this.mediainfo.longDescription || this.mediainfo.description;
thanks for the suggestion

2021-05-24 10:20 UTC, merged

2021-05-24 10:20 UTC, mister-ben commented
Thanks!

2021-05-24 11:36 UTC, lanmengyujing commented
@mister-ben thanks for help merge the pull request. How can I get the latest code for this plugin?
Can I use this https://cdn.jsdelivr.net/npm/videojs-schema/dist/videojs-schema.min.js?

2021-05-24 15:28 UTC, mister-ben commented
I just published a new version to NPM, jsdelivr etc will return that soon although I'm not sure how long they cache. For me https://cdn.jsdelivr.net/npm/videojs-schema@latest/dist/videojs-schema.min.js is already returning v0.5.0.

2021-05-25 00:26 UTC, lanmengyujing commented
@mister-ben thanks for helping publish the new version to NPM. How can I use this library using ES6 module **import** with https://github.com/brightcove/react-player-loader ?
I did not find any documentation about it.  Appreciate it if there is a demo or any documentation I can refer to.

2021-05-26 05:43 UTC, mister-ben commented
With react player loader, you may need to register the plugin on the `window.videojs` created by the player script, on the player success callback

```js
import window from "global/window";
import schema from "videojs-schema";
```

```js
const onSuccess = function (success) {
  const player = success.ref;
  if (!player.hasPlugin("schema")) {
    window.videojs.registerPlugin("schema", schema);
  }
  player.schema();
};
```

```js
ReactDOM.render( <BrightcovePlayer onSuccess={onSuccess} ...
```

Adding the script to the player config is recommended instead.

2021-05-31 02:23 UTC, lanmengyujing commented
@mister-ben Thanks for sharing the code, that really helps.
Why the recommended way is adding the schema script to the player config?  Are there any drawbacks of using this video schema plugin with ES import?